name: surpraise_infra
publish_to: none
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  surpraise_backend_dependencies:
    git:
      https://github.com/viniciusamelio/surpraise_backend_dependencies
  surpraise_core: 
    git: https://github.com/viniciusamelio/surpraise_core
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  faker: ^2.0.0
  mocktail: ^0.3.0

