name: surpraise_infra
publish_to: none
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  mongo_dart: ^0.7.4+1
  surpraise_core: 
    git: git@github.com:viniciusamelio/surpraise_core.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  faker: ^2.0.0

